# Generated by Django 3.2.5 on 2022-05-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dailyorgrunningtotal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagecosts',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dates'),
        ),
    ]
