# Generated by Django 3.2.5 on 2022-05-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_storagecosts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagecosts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.projects'),
        ),
    ]
